# Generated by Django 3.2.9 on 2021-12-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=100)),
                ('mobile_number', models.IntegerField()),
            ],
        ),
    ]
